const Foods = [
  {
    index: 0,
    name: "Casandra Brock",
    balance: "$196",
    url: "/restaurant-luxury/images/foods/food-1.png",
  },
  {
    index: 1,
    name: "Ingram Kane",
    balance: "$193",
    url: "/restaurant-luxury/images/foods/food-2.png",
  },
  {
    index: 2,
    name: "Lucinda Brooks",
    balance: "$179",
    url: "/restaurant-luxury/images/foods/food-3.png",
  },
  {
    index: 3,
    name: "Bertie Gonzales",
    balance: "$109",
    url: "/restaurant-luxury/images/foods/food-4.png",
  },
  {
    index: 4,
    name: "Annette Floyd",
    balance: "$13",
    url: "/restaurant-luxury/images/foods/food-5.png",
  },
  {
    index: 5,
    name: "Joyner Mooney",
    balance: "$163",
    url: "/restaurant-luxury/images/foods/food-6.png",
  },
  {
    index: 6,
    name: "Carrie Randolph",
    balance: "$115",
    url: "/restaurant-luxury/images/foods/food-7.jpg",
  },
  {
    index: 7,
    name: "Barry Barnes",
    balance: "$142",
    url: "/restaurant-luxury/images/foods/food-8.png",
  },
  {
    index: 8,
    name: "Prince Kirkland",
    balance: "$137",
    url: "/restaurant-luxury/images/thumbnails/thumb-1.jpg",
  },
  {
    index: 9,
    name: "Fitzpatrick Wilder",
    balance: "$140",
    url: "/restaurant-luxury/images/thumbnails/thumb-2.jpg",
  },
  {
    index: 10,
    name: "Janelle Bridges",
    balance: "$49",
    url: "/restaurant-luxury/images/thumbnails/thumb-3.jpg",
  },
  {
    index: 11,
    name: "Deborah Shelton",
    balance: "$84",
    url: "/restaurant-luxury/images/thumbnails/thumb-4.jpg",
  },
  {
    index: 12,
    name: "Tania Gallegos",
    balance: "$85",
    url: "/restaurant-luxury/images/thumbnails/thumb-5.jpg",
  },
  {
    index: 13,
    name: "Sharlene Fleming",
    balance: "$71",
    url: "/restaurant-luxury/images/thumbnails/thumb-6.jpg",
  },
];

const Blogs = [
  {
    index: 0,
    created: "2021-03-10T02:25:02",
    avatar: "/restaurant-luxury/images/authors/person-2.jpeg",
    title: "pariatur enim Lorem cillum deserunt est officia dolor ipsum labore elit esse qui eiusmod officia incididunt id fugiat dolor mollit",
    intro: "Anim aliquip laborum dolor Lorem laborum commodo ad. Non ex veniam nostrud qui dolore aliqua id fugiat.",
    name: "Elise Daugherty",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 1,
    created: "2021-03-24T01:48:25",
    avatar: "/restaurant-luxury/images/authors/person-6.jpeg",
    title: "officia culpa dolore laboris veniam aliquip fugiat ad et mollit irure voluptate enim proident sunt mollit veniam occaecat consectetur irure",
    intro: "Labore dolor elit deserunt ullamco ea. Anim et aliqua ea culpa officia laborum fugiat anim aliquip ut in quis.",
    name: "Shields Santana",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 2,
    created: "2020-04-25T09:37:41",
    avatar: "/restaurant-luxury/images/authors/person-5.jpeg",
    title: "ea ea minim ad non nisi nulla qui ullamco et excepteur mollit deserunt laborum commodo occaecat adipisicing exercitation magna commodo",
    intro:
      "Dolor enim sunt est nostrud ea id cupidatat qui incididunt eiusmod nisi aliquip aliquip. Quis consequat aliquip occaecat voluptate nisi ex aliquip elit esse anim eu cupidatat exercitation.",
    name: "Rachelle Bell",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 3,
    created: "2020-01-12T05:02:34",
    avatar: "/restaurant-luxury/images/authors/person-3.jpeg",
    title: "anim mollit eiusmod sit qui laborum voluptate qui mollit amet qui tempor do ipsum laborum minim nisi fugiat cupidatat duis",
    intro:
      "Ad irure culpa Lorem labore tempor officia tempor in nostrud reprehenderit ipsum culpa. Occaecat qui in consectetur labore esse ipsum aliquip consequat aliqua id dolore veniam.",
    name: "Brandie Allison",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 4,
    created: "2020-07-06T08:27:48",
    avatar: "/restaurant-luxury/images/authors/person-2.jpeg",
    title: "culpa pariatur quis amet nisi ea ipsum nisi voluptate non deserunt culpa adipisicing duis ad veniam eiusmod nostrud ut aliqua",
    intro:
      "Voluptate eu aliqua do ex. Exercitation laboris exercitation tempor ex fugiat veniam incididunt proident officia ipsum exercitation aliqua pariatur ullamco.",
    name: "Courtney Moody",
  },
  {
    index: 5,
    created: "2020-09-28T09:36:54",
    avatar: "/restaurant-luxury/images/authors/person-7.jpeg",
    title: "aute incididunt commodo sunt mollit qui aliquip consectetur adipisicing nulla magna ea sunt ipsum veniam excepteur sunt ex elit aliqua",
    intro: "Ea laborum exercitation qui amet. Lorem id consectetur anim ullamco fugiat.",
    name: "Lloyd Dyer",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 6,
    created: "2020-02-10T02:12:10",
    avatar: "/restaurant-luxury/images/authors/person-8.jpeg",
    title: "officia proident consectetur deserunt elit non cillum ea reprehenderit Lorem sint commodo sit dolor duis aliqua incididunt aute est irure",
    intro: "Eiusmod nostrud laboris dolor aliqua excepteur minim. Ut mollit mollit minim magna culpa aliqua esse adipisicing esse.",
    name: "Gaines Cobb",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 7,
    created: "2020-04-14T05:01:49",
    avatar: "/restaurant-luxury/images/authors/person-2.jpeg",
    title: "consequat sit esse qui do voluptate irure veniam voluptate velit nisi cillum proident in quis excepteur enim mollit esse dolore",
    intro: "Sunt culpa excepteur aute laboris velit magna non duis id. Ad in aliqua nisi commodo excepteur ullamco nostrud enim et dolore proident.",
    name: "Leila Thomas",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 8,
    created: "2020-01-17T11:25:54",
    avatar: "/restaurant-luxury/images/authors/person-9.jpeg",
    title: "aliquip proident labore occaecat incididunt anim proident occaecat dolor quis sit deserunt eiusmod mollit dolor amet eu minim ad magna",
    intro: "Ipsum anim deserunt aute labore laboris irure aliqua do laboris non elit. Pariatur aliqua ullamco do ad elit adipisicing.",
    name: "Bernadine Glenn",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 9,
    created: "2020-11-11T08:50:24",
    avatar: "/restaurant-luxury/images/authors/person-9.jpeg",
    title: "incididunt ea pariatur consectetur fugiat qui nostrud enim nostrud fugiat aute veniam occaecat commodo commodo proident adipisicing mollit sit do",
    intro: "Et fugiat irure sit ullamco ad aute proident et cupidatat ut proident eiusmod duis. Aliqua adipisicing officia anim incididunt aliquip enim qui.",
    name: "Sanchez Acosta",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 10,
    created: "2020-01-24T01:22:27",
    avatar: "/restaurant-luxury/images/authors/person-8.jpeg",
    title: "officia dolor est culpa labore commodo sit qui sunt consequat cupidatat nostrud qui consequat tempor et veniam anim duis fugiat",
    intro:
      "Consequat deserunt duis dolore irure laborum ea quis eu eu ad. Cillum esse laboris proident non sunt commodo excepteur aliquip minim mollit tempor ut voluptate.",
    name: "Vega Padilla",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 11,
    created: "2020-08-22T06:49:47",
    avatar: "/restaurant-luxury/images/authors/person-9.jpeg",
    title: "anim laboris pariatur enim cillum in labore est esse mollit cupidatat exercitation culpa nulla aliqua incididunt tempor anim voluptate Lorem",
    intro: "Pariatur est aliqua velit Lorem pariatur tempor velit sunt nostrud. Non exercitation cupidatat exercitation quis duis nulla.",
    name: "Hines Olsen",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 12,
    created: "2021-02-07T08:14:46",
    avatar: "/restaurant-luxury/images/authors/person-3.jpeg",
    title: "pariatur sint et adipisicing fugiat ullamco minim magna amet irure eiusmod irure laborum cillum ut nulla proident sit est eiusmod",
    intro: "Ad consectetur quis nostrud nostrud nulla consequat ipsum consequat exercitation duis esse reprehenderit. Dolor nostrud commodo ad qui irure.",
    name: "Stein Soto",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 13,
    created: "2020-04-04T12:15:52",
    avatar: "/restaurant-luxury/images/authors/person-6.jpeg",
    title: "nostrud irure ad quis nostrud sint eiusmod eiusmod esse cupidatat excepteur sunt est culpa pariatur nostrud sunt exercitation ad ipsum",
    intro: "Nisi labore officia commodo ad aliquip. Pariatur sit ullamco do ullamco voluptate.",
    name: "Neal Boyer",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 14,
    created: "2020-03-05T04:57:06",
    avatar: "/restaurant-luxury/images/authors/person-6.jpeg",
    title: "magna id velit eu dolor id sint eu labore velit velit elit adipisicing ad eiusmod deserunt reprehenderit excepteur elit exercitation",
    intro: "Incididunt deserunt exercitation laborum incididunt cillum reprehenderit laborum quis. Aliquip culpa ipsum aute eu nisi esse velit occaecat in.",
    name: "Andrea Sims",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 15,
    created: "2020-04-07T04:07:02",
    avatar: "/restaurant-luxury/images/authors/person-7.jpeg",
    title: "consectetur et consequat minim esse tempor laboris sint qui aliqua eiusmod ea eu magna aute anim nostrud nisi fugiat nostrud",
    intro: "Do deserunt dolore reprehenderit velit id dolore eu magna id consequat tempor eu anim. Fugiat cillum cupidatat id Lorem enim.",
    name: "Hawkins Wyatt",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 16,
    created: "2020-08-17T08:27:39",
    avatar: "/restaurant-luxury/images/authors/person-1.jpeg",
    title: "Lorem duis exercitation qui occaecat eu est ad excepteur sit do duis sint ea magna enim quis cupidatat sint laborum",
    intro: "Nisi deserunt sit ad eu anim. Duis sunt dolore ut veniam esse sunt.",
    name: "Opal Joseph",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 17,
    created: "2020-04-09T11:59:57",
    avatar: "/restaurant-luxury/images/authors/person-2.jpeg",
    title:
      "enim nisi consequat elit cupidatat excepteur consequat dolore laborum occaecat officia cillum incididunt sint qui consequat culpa adipisicing nostrud non",
    intro: "In id do eiusmod aliquip. Lorem occaecat pariatur laborum do.",
    name: "Christine Doyle",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 18,
    created: "2020-05-27T10:42:18",
    avatar: "/restaurant-luxury/images/authors/person-6.jpeg",
    title: "nisi esse reprehenderit non incididunt eiusmod sunt aliquip anim anim ex nostrud dolor mollit enim reprehenderit minim veniam voluptate dolore",
    intro:
      "Culpa et exercitation reprehenderit adipisicing aute elit esse sunt pariatur voluptate. Amet laborum mollit in ullamco consequat anim enim consequat est sunt nostrud elit ullamco laboris.",
    name: "Deleon Bartlett",
    url: "/restaurant-luxury/blog1.html",
  },
  {
    index: 19,
    created: "2020-10-29T12:43:02",
    avatar: "/restaurant-luxury/images/authors/person-1.jpeg",
    title: "qui voluptate culpa proident Lorem commodo sit dolor ipsum dolor ex labore laborum ullamco nisi occaecat tempor sit ad voluptate",
    intro: "Et elit dolore pariatur ut deserunt amet dolor aute exercitation laborum exercitation cillum. Ea laborum est fugiat consequat veniam.",
    name: "Katy Christensen",
    url: "/restaurant-luxury/blog1.html",
  },
];

export { Foods, Blogs };
